### ISSUE TITLE
Are you thinking redo by rust

### ISSUE THREAD

**Issue by Antake2333** [damartripamungkas/botdexdamar#1]
Are you thinking redo by rust

**Comment by damartripamungkas** [comment]
can you explain what you mean?

**Comment by Antake2333** [comment]
Implementing sandwiches with Rust is more efficient

damartripamungkas ***@***.***>于2021年11月23日 周二下午12:09写道：

**Comment by Antake2333** [comment]
We can cooperation.Recode by rust


Antake也 ***@***.***>于2021年11月23日 周二下午12:11写道：

**Comment by damartripamungkas** [comment]
I think nodejs is faster and more flexible than rust
