### ISSUE TITLE
Why advertise on github?

### ISSUE THREAD

**Issue by TomiLikesToCode** [damartripamungkas/botdexdamar#10]

**Comment by damartripamungkas** [comment]
why do you ask that?

**Comment by DawoodKMasood** [comment]
> why do you ask that?

GitHub's primary purpose is for sharing and collaborating on code. It's a bit like setting up a lemonade stand in a library — not exactly the right audience or place.

**Comment by damartripamungkas** [comment]
> > why do you ask that?
> 
> GitHub's primary purpose is for sharing and collaborating on code. It's a bit like setting up a lemonade stand in a library — not exactly the right audience or place.

Yes, I know that, basically you are asking that to get the code, right?

**Comment by DawoodKMasood** [comment]
> Yes, I know that, basically you are asking that to get the code, right?

Actually, my point wasn't about accessing the code at all. I was highlighting the foundational principle of GitHub. Your approach just seemed a bit out of place on a platform built on those ideals.

**Comment by ekarve** [comment]
> > Yes, I know that, basically you are asking that to get the code, right?
> 
> Actually, my point wasn't about accessing "the code" at all. I was highlighting the foundational principle of GitHub. Your approach just seemed a bit out of place on a platform built on those ideals.

Scammers man

**Comment by damartripamungkas** [comment]
I will close this if there are no more questions
