### ISSUE TITLE
Be Careful

### ISSUE THREAD

**Issue by 0xlurking** [damartripamungkas/botdexdamar#6]
Seems realy scummy, buying process needs multiple weeks, while he raises the prices multiple times.

Everything here is open source and there are other Bots with much better support.

but sure you can waste 2000$ aswell lol

**Comment by damartripamungkas** [comment]
what do you mean?  have you contacted me via telegram?

**Comment by damartripamungkas** [comment]
fudder

**Comment by 0xlurking** [comment]
its not fud. Its wasted money imo.
There are other Bots for 1k+$ which offer the same and much better support.

**Comment by damartripamungkas** [comment]
beri saya link untuk bot lain nya?

**Comment by damartripamungkas** [comment]
give me the link of the bot website you mean? anyway my bot is $1600 not $2K

**Comment by DawoodKMasood** [comment]
Lmao, talk about selling something on open-source platform.

**Comment by damartripamungkas** [comment]
closed because there is no answer
